<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class loginadmin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true)
		{
			redirect('Welcome/homeadmin');
		}
		
		if(!$this->input->post())
		{
			$this->load->view('Welcome/homeadmin');
		}
		else
		{
			$chek=$this->Admin->cekadmin(
				$this->input->post('username_admin'),
				$this->input->post('password_admin'));
			
			if (!empty($chek)) {
				$this->session->set_userdata('logined',true);
				$this->session->set_userdata('nama_admin',$chek->nama_admin);
				redirect('Welcome/homeadmin');
			}else{
				redirect("Welcome/awal");
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		$this->session->unset_userdata('nama_admin');
		redirect("Welcome/awal");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */